### ISSUE TITLE
Browserify-example with replicating needs JSON content installed

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#172]
Testing the browserify-example [browserify-replicate-full-index-to-browser](https://github.com/fergiemcdowall/search-index/tree/master/doc/examples/browserify-replicate-full-index-to-browser)

The indexgenerator.js, I'm guessing, fails because of missing [reuters-21578-json](https://github.com/fergiemcdowall/reuters-21578-json). Should be added as prerequisit?
```
Espens-MacBook-Pro:browserify-test eklem$ node indexgenerator.js
module.js:338
    throw err;
          ^
Error: Cannot find module '../../../node_modules/reuters-21578-json/data/justTen/justTen.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/eklem/node_modules/search-index/doc/examples/browserify-test/indexgenerator.js:1:77)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by fergiemcdowall** [comment]
hmm- have you done npm install on the main project? Come to think of it, maybe these projects should be extracted out into their own modules, and the example links just point to them

**Comment by eklem** [comment]
My bad. I forgot (didn't know/didn't remember the npm install thingy). So rolling back the ../../-fix.
