### ISSUE TITLE
Browserify-example replicating index  fails on brfs

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#174]
[browserify-replicate-full-index-to-browser](https://github.com/fergiemcdowall/search-index/tree/master/doc/examples/browserify-replicate-full-index-to-browser) needs to have `brfs` installed, in addition to browserify. I've checked that I've got it installed, but still I get this error message:

```
eklem$ browserify -t brfs main.js > bundle.js
Error: Cannot find module 'brfs' from '/Users/eklem/node_modules/search-index/doc/examples/browserify-test'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by fergiemcdowall** [comment]
So much brokeness in the examples at the moment- they really need tests set up for them

**Comment by eklem** [comment]
Not a bug, I forgot npm install on search-index
