### ISSUE TITLE
Fails when adding items with long arrays in filter fields

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#305]
```console
/Users/eklem/git_modules/search-index-indexer/node_modules/search-index/node_modules/levelup/node_modules/level-codec/index.js:34
  return this._valueEncoding(opts, batchOpts).encode(value);
                                              ^

RangeError: Invalid string length
    at Object.stringify [as encode] (native)
    at Codec.encodeValue (/Users/eklem/git_modules/search-index-indexer/node_modules/search-index/node_modules/levelup/node_modules/level-codec/index.js:34:47)
    at /Users/eklem/git_modules/search-index-indexer/node_modules/search-index/node_modules/levelup/node_modules/level-codec/index.js:56:23
    at Array.map (native)
    at Codec.encodeBatch (/Users/eklem/git_modules/search-index-indexer/node_modules/search-index/node_modules/levelup/node_modules/level-codec/index.js:48:14)
    at LevelUP.batch (/Users/eklem/git_modules/search-index-indexer/node_modules/search-index/node_modules/levelup/lib/levelup.js:307:26)
    at /Users/eklem/git_modules/search-index-indexer/node_modules/search-index/node_modules/search-index-adder/index.js:228:30
    at /Users/eklem/git_modules/search-index-indexer/node_modules/search-index/node_modules/async/lib/async.js:52:16
    at /Users/eklem/git_modules/search-index-indexer/node_modules/search-index/node_modules/async/lib/async.js:269:32
    at /Users/eklem/git_modules/search-index-indexer/node_modules/search-index/node_modules/async/lib/async.js:44:16
```

To reproduce:

```console
$ npm install search-index-searcher
```
and then:
```
$ node --max-old-space-size=12288 index.js -c https://raw.githubusercontent.com/eklem/recipes-klikk-dataset/master/config.json -d https://raw.githubusercontent.com/eklem/recipes-klikk-dataset/master/klikk-recipes.json -s 5054 -e 5054
```

Should maybe cut off too long arrays. That would be the best I think. Second best would be to fail gracefully and give a meaningful error message.

**Comment by eklem** [comment]
And to be a bit more clear. The array is on a field that is used for a filer:
```json
{
    "batchname": "recipes",
    "nGramLength": [
        1
    ],
    "fieldOptions": [
        {
            "fieldName": "ingredients",
            "filter": true
        }
    ]
}
```
This one item crashes search-index, or one of it's dependencies. But it seems that long arrays, and not so long as to crash it alone, will make the memory use sky rocket and possibly crash node because of too little memory available.

**Comment by fergiemcdowall** [comment]
Ah yes. If there are a lot of elements in an array in a filter field then that will cause problems. I am rewriting the indexing pipeline just now- will test for this.

**Comment by fergiemcdowall** [comment]
Filter fields are no longer a thing. This is probably fixed, but I guess we need a test case to make sure

**Comment by eklem** [comment]
Nice! I'll assemble some content and re-test when 0.9 is on NPM. And you can add it to the automated tests.

**Comment by fergiemcdowall** [comment]
I'm just having a tidy up, and I'm pretty sure that this is fixed- so I'll close this just now, reopen if it is still a problem with `0.9.0`
