### ISSUE TITLE
TypeError: Cannot read property 'info' of undefined

### ISSUE THREAD

**Issue by jacargentina** [fergiemcdowall/search-index#323]
I'm getting this when finishing an indexing

```
/home/.../node_modules/search-index/lib/siUtil.js:33
       siOptions.log.info('closed...')
                    ^

TypeError: Cannot read property 'info' of undefined
    at /home/.../node_modules/search-index/lib/siUtil.js:33:21
    at /home/.../node_modules/levelup/lib/levelup.js:141:18
    at /home/.../node_modules/abstract-leveldown/abstract-leveldown.js:65:7

```

**Comment by fergiemcdowall** [comment]
I just pushed `search-index@0.9.3` which hopefully fixed this

**Comment by fergiemcdowall** [comment]
...and published it to npm
