### ISSUE TITLE
Module version mismatch error

### ISSUE THREAD

**Issue by revansdxr** [fergiemcdowall/search-index#339]
I receive the following error when I try to use the module:

Module version mismatch. Expected 46, got 47.

Error: Module version mismatch. Expected 46, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at bindings (/media/psf/websites/git/nursing.avalon.local/Web_Site_SSL/nursingjs/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/media/psf/websites/git/nursing.avalon.local/Web_Site_SSL/nursingjs/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/media/psf/websites/git/nursing.avalon.local/Web_Site_SSL/nursingjs/node_modules/search-index/lib/index.js:3:14)
    at Module._compile (module.js:410:26)

**Comment by revansdxr** [comment]
Appears to be a node version issue.  I upgraded from v4 to v6.91 and the issue resolved after a npm rebuild.

**Comment by fergiemcdowall** [comment]
👍
