### ISSUE TITLE
TypeError: Cannot read property 'concat' of undefined

### ISSUE THREAD

**Issue by fdelavega** [fergiemcdowall/search-index#371]
Hi,

I have rebuild my project dependencies and the search-index lib has started giving an exception when executing queries. In particular:

TypeError: Cannot read property 'concat' of undefined
    at /home/francisco/Trabajo/TMForum/fiware-pep-proxy/node_modules/search-index-searcher/lib/MergeOrConditions.js:33:56
    at Array.reduce (native)
    at MergeOrConditions._flush (/home/francisco/Trabajo/TMForum/fiware-pep-proxy/node_modules/search-index-searcher/lib/MergeOrConditions.js:23:6)
    at MergeOrConditions.<anonymous> (_stream_transform.js:118:12)
    at MergeOrConditions.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at MergeOrConditions.emit (events.js:185:7)
    at prefinish (_stream_writable.js:505:12)
    at finishMaybe (_stream_writable.js:513:7)
    at endWritable (_stream_writable.js:525:3)
    at MergeOrConditions.Writable.end (_stream_writable.js:490:5)
    at ScoreDocsOnField.onend (_stream_readable.js:511:10)
    at ScoreDocsOnField.g (events.js:291:16)

Debuging, I have seen that the line throwing the exeception is the following one:

lastDoc.scoringCriteria = lastDoc.scoringCriteria.concat(cur.scoringCriteria)

it is trying to read a property scoringCriteria from lastDoc; nevertheless, lastDoc is the following:
{ id: 'catalog:1', score: 1 }

No scoringCriteria property

I am using version 0.9.15, I have tried to update to version 0.9.17 and 0.10.0 with the same result

**Comment by fergiemcdowall** [comment]
Hmmm- I haven't seen that error before. Could you provide a little script or recipe that reproduces the issue?

**Comment by fdelavega** [comment]
This was a running example I had:

https://github.com/fdelavega/index-example

This example was running. I have removed the node_modules dir and executed again npm install, without modifing anything in the code, nor in the package.json, and this is the output:

francisco@fran-equipo:~/Trabajo/index-example$ node example.js 
Init index
Loading data
product:101
product:4
product:56
product:151
product:156
/home/francisco/Trabajo/index-example/node_modules/search-index-searcher/lib/MergeOrConditions.js:30
      lastDoc.scoringCriteria = lastDoc.scoringCriteria.concat(cur.scoringCriteria)
                                                       ^

TypeError: Cannot read property 'concat' of undefined
    at /home/francisco/Trabajo/index-example/node_modules/search-index-searcher/lib/MergeOrConditions.js:30:56
    at Array.reduce (native)
    at MergeOrConditions._flush (/home/francisco/Trabajo/index-example/node_modules/search-index-searcher/lib/MergeOrConditions.js:23:6)
    at MergeOrConditions.<anonymous> (_stream_transform.js:118:12)
    at MergeOrConditions.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at MergeOrConditions.emit (events.js:185:7)
    at prefinish (_stream_writable.js:505:12)
    at finishMaybe (_stream_writable.js:513:7)
    at endWritable (_stream_writable.js:525:3)

**Comment by fdelavega** [comment]
An update on this, with version 0.9.15 installed, I have downgraded search-index-searcher from version 0.1.28 (the one that is now installed by default) to version 0.1.27 and it worked again

**Comment by Cazaril** [comment]
Another update, the error is still showing in version 0.2.0 of search-index-searcher

**Comment by fergiemcdowall** [comment]
This should now work.
