### ISSUE TITLE
Object.keys issue in sample app

### ISSUE THREAD

**Issue by shawngiese** [fergiemcdowall/search-index#444]
Any suggestions how to overcome this error? Running on Windows 10, node v8.11.1.

search > lion

7 : RED LION INNS FILES PLANS OFFERING
\indexer2\test.js:45
    const terms = Object.keys(data.scoringCriteria[0].df).map(function(item) {
                         ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at FetchStoredDoc.printResults (C:\Users\me\Documents\heroku\indexer2\te
st.js:45:26)
    at emitOne (events.js:116:13)
    at FetchStoredDoc.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at FetchStoredDoc.Readable.push (_stream_readable.js:208:10)
    at FetchStoredDoc.Transform.push (_stream_transform.js:147:32)
    at C:\Users\me\Documents\heroku\indexer2\node_modules\search-index-searc
her\lib\FetchStoredDoc.js:19:10
    at C:\Users\me\Documents\heroku\indexer2\node_modules\search-index\node_
modules\levelup\lib\levelup.js:211:7

**Comment by ronnyroeller** [comment]
It looks like the response object changed. Changing the second line in the `printResults` method seems to do the trick:
```
const terms = data.scoringCriteria[0].matches.map(item => item.term);
```

**Comment by fergiemcdowall** [comment]
thanks @ronnyroeller - will fix this ASAP

**Comment by fergiemcdowall** [comment]
Sample app is no more- new sample app coming...
