### ISSUE TITLE
document using memdown

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#464]
Test first

**Comment by eklem** [comment]
Added stuff from tests, but need to make a working example to make it accurate.

**Comment by eklem** [comment]
Make an extra version of the demo that uses memdown. Got it working over at [designing-with-search-data](https://github.com/eklem/designing-with-search-data).

**Comment by eklem** [comment]
Have something working over at [`designing-with-search-data`](https://github.com/eklem/designing-with-search-data/commit/8a1079f2588b8bc09c67cc531372ff76366b155d)

**Comment by fergiemcdowall** [comment]
This is now (briefly) documented here -> https://github.com/fergiemcdowall/search-index/blob/master/docs/FAQ.md#can-i-use-another-backend-like-mysql-or-redis

Does it make sense or is it too cryptic?

**Comment by eklem** [comment]
I think it makes sense. Will try

**Comment by tonprince** [comment]
I could connect to the Redis instance:

```
let redis = new Redis("redis....:35034");
let db = redisdown("tripstorekrabi")
db.open({ redis }, async (err) => {
  if (err) {
    rej(err);
  } else {
    let { PUT } = await si({ db });
    await PUT([{ "_id": "111122", "test": "hello world" }]);
  }
});
```

but always gets the following error:

```
TypeError: this._end is not a function
    at Iterator.AbstractIterator.end (/Users/tonprincepro/Dropbox/Tripstore/Website/workspace/com.tripstorekrabi/hero/api/booking/node_modules/abstract-leveldown/abstract-iterator.js:67:8)
    at Iterator._end (/Users/tonprincepro/Dropbox/Tripstore/Website/workspace/com.tripstorekrabi/hero/api/booking/node_modules/encoding-down/index.js:150:11)
    at Iterator.AbstractIterator.end (/Users/tonprincepro/Dropbox/Tripstore/Website/workspace/com.tripstorekrabi/hero/api/booking/node_modules/abstract-leveldown/abstract-iterator.js:67:8)
    at ReadStream._destroy (/Users/tonprincepro/Dropbox/Tripstore/Website/workspace/com.tripstorekrabi/hero/api/booking/node_modules/level-iterator-stream/index.js:40:18)
    at ReadStream.destroy (/Users/tonprincepro/Dropbox/Tripstore/Website/workspace/com.tripstorekrabi/hero/api/booking/node_modules/readable-stream/lib/internal/streams/destroy.js:35:8)
    at ReadStream.emit (node:events:406:35)
    at endReadableNT (/Users/tonprincepro/Dropbox/Tripstore/Website/workspace/com.tripstorekrabi/hero/api/booking/node_modules/readable-stream/lib/_stream_readable.js:1094:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by fergiemcdowall** [comment]
Hmm- interesting. I will keep this open as a bug for just now, and look into it when I have time.

 @tonprince  Please keep us posted if you find a solution!
