### ISSUE TITLE
Question about indexeddb declaration

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#473]
Hi @fergiemcdowall !
I'm trying to webpack search-index to use in Adobe XD plugin environment over at [designing-with-search-data](https://github.com/eklem/designing-with-search-data). I'm doing mostly what worked for the browser, using memdown, but get an error that indexeddb is not defined.

Here's the error message in XD (from Developer console) when trying to load the plugin

```console
Loading plugin /Users/eklem/Library/Application Support/Adobe/Adobe XD/develop/designing-with-search-data
Plugin Error: Error loading plugin /Users/eklem/Library/Application Support/Adobe/Adobe XD/develop/designing-with-search-data
Plugin ReferenceError: indexedDB is not defined
    at Object.<anonymous> (/Users/eklem/Library/Application Support/Adobe/Adobe XD/develop/designing-with-search-data/XD-webpacked.js:8630:39)
    at Object../node_modules/level-js/index.js (/Users/eklem/Library/Application Support/Adobe/Adobe XD/develop/designing-with-search-data/XD-webpacked.js:8814:30)
    at __webpack_require__ (/Users/eklem/Library/Application Support/Adobe/Adobe XD/develop/designing-with-search-data/XD-webpacked.js:20:30)
    at Object../node_modules/level/browser.js (/Users/eklem/Library/Application Support/Adobe/Adobe XD/develop/designing-with-search-data/XD-webpacked.js:9097:111)
    at __webpack_require__ (/Users/eklem/Library/Application Support/Adobe/Adobe XD/develop/designing-with-search-data/XD-webpacked.js:20:30)
    at Module../node_modules/fergies-inverted-index/dist/fergies-inverted-index.esm.js (/Users/eklem/Library/Application Support/Adobe/Adobe XD/develop/designing-with-search-data/XD-webpacked.js:5775:63)
    at __webpack_require__ (/Users/eklem/Library/Application Support/Adobe/Adobe XD/develop/designing-with-search-data/XD-webpacked.js:20:30)
    at Module../XD-webpackable.js (/Users/eklem/Library/Application Support/Adobe/Adobe XD/develop/designing-with-search-data/XD-webpacked.js:4510:80)
    at __webpack_require__ (/Users/eklem/Library/Application Support/Adobe/Adobe XD/develop/designing-with-search-data/XD-webpacked.js:20:30)
    at /Users/eklem/Library/Application Support/Adobe/Adobe XD/develop/designing-with-search-data/XD-webpacked.js:84:18
    at convertPluginErrorToString (plugins/PluginErrorUtil.js:1:198)
    at internalFormatPluginError (plugins/PluginErrorUtil.js:1:1065)
    at internalReportPluginError (plugins/PluginErrorUtil.js:1:1172)
    at Object.reportPluginError (plugins/PluginErrorUtil.js:1:1604)
    at loadPlugin (plugins/PluginLoader.js:1:673)
    at plugins/PluginLoader.js:1:6211
    at Array.forEach (<anonymous>)
    at reloadPlugins (plugins/PluginLoader.js:1:6191)
    at Artwork.history.waitForCurrentEditBatch.then (plugins/PluginLoader.js:1:6850)
```

My question: Is there some code in search-index (or fii I guess) that references indexeddb, or is based upon indexeddb already being referenced/declared?

**Comment by fergiemcdowall** [comment]
The tests currently run a webpack bundle like so `npm run empty-sandbox && webpack && cat test/sandbox/bundle.js | tape-run`. Its been a while since I took a good look at this, but there is some webpack config that is needed to make it work in the browser (https://github.com/fergiemcdowall/search-index/blob/master/webpack.config.babel.js). 

When I get a couple of hours I will update the doc with a HOWTO for using with webpack and rollup

**Comment by eklem** [comment]
I get it working for the browser, just not similar code in Adobe XD. I'll try to use the Webpack config used in the test.

**Comment by fergiemcdowall** [comment]
OK!

**Comment by eklem** [comment]
It seems it's `level-js` that expects `indexedDB` to be there, and `memdown` works well as long as indexedDB is still around (since it's referenced in level-js).

**Comment by eklem** [comment]
I think I figured it out with `indexedDB` not being globally declared. Not sure how to do that properly, but patched level-js/index.js with this at the beginning:
```javascript
var indexedDB
```

So, closing this for now, and have to figure it out how to do this without tampering with level-js.

And, @fergiemcdowall ... check it out. search-index running in Adobe XD for the very first time in history 😄 

<img width="1072" alt="Screenshot 2019-04-26 at 15 04 16" src="https://user-images.githubusercontent.com/236656/56809738-e456e980-6834-11e9-8d62-9f10fbfe9585.png">

**Comment by fergiemcdowall** [comment]
@eklem it is a thing of beauty! :)
