### ISSUE TITLE
Travis-CI fail on npm install for nodejs v12

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#490]
https://travis-ci.org/fergiemcdowall/search-index/builds/567840468
(you need to re-start it to see what's happening in the log)

**Comment by eklem** [comment]
<img width="1072" alt="Screenshot 2019-08-05 at 13 57 56" src="https://user-images.githubusercontent.com/236656/62462960-0db6d800-b789-11e9-9aa5-efcd25f52106.png">

**Comment by fergiemcdowall** [comment]
Hmm- not seen that one before...

**Comment by eklem** [comment]
Tested once more, locally. Got this error. Attached the log. Googled some, but nothing screams eureca.

Maybe update leveldown dependency from 3.0.2?
https://github.com/Level/leveldown/blob/master/package.json



```console
Oles-MacBook-Pro-2:search-index eklem$ npm install

> fsevents@1.2.9 install /Users/eklem/git_modules/search-index/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
[fsevents] Success: "/Users/eklem/git_modules/search-index/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> leveldown@5.1.0 install /Users/eklem/git_modules/search-index/node_modules/leveldown
> node-gyp-build


> leveldown@3.0.2 install /Users/eklem/git_modules/search-index/node_modules/level-out/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.1.0 runtime=node arch=x64 platform=darwin)
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_set.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix_sse.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/hash.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env_posix.o
  LIBTOOL-STATIC Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy.o
  LIBTOOL-STATIC Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/batch.o
In file included from ../src/batch.cc:3:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1: warning: 'ToBoolean' is deprecated: ToBoolean can never throw. Use Local version.
      [-Wdeprecated-declarations]
X(Boolean)
^
../../nan/nan_converters_43_inl.h:18:12: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
           ^
<scratch space>:213:1: note: expanded from here
ToBoolean
^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:2523:3: note: 'ToBoolean' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("ToBoolean can never throw. Use Local version.",
  ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:3:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:40:1: warning: 'BooleanValue' is deprecated: BooleanValue can never throw. Use Isolate version.
      [-Wdeprecated-declarations]
X(bool, Boolean)
^
../../nan/nan_converters_43_inl.h:37:15: note: expanded from macro 'X'
  return val->NAME ## Value(isolate->GetCurrentContext());                     \
              ^
<scratch space>:220:1: note: expanded from here
BooleanValue
^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:2561:3: note: 'BooleanValue' has been explicitly marked deprecated here
  V8_DEPRECATED("BooleanValue can never throw. Use Isolate version.",
  ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:3:
In file included from ../../nan/nan.h:203:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:103:42: error: no viable conversion from 'v8::Isolate *' to 'Local<v8::Context>'
  return scope.Escape(v8::Function::New( isolate
                                         ^~~~~~~
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:183:7: note: candidate constructor (the implicit copy constructor) not
      viable: no known conversion from 'v8::Isolate *' to 'const v8::Local<v8::Context> &' for 1st argument
class Local {
      ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:183:7: note: candidate constructor (the implicit move constructor) not
      viable: no known conversion from 'v8::Isolate *' to 'v8::Local<v8::Context> &&' for 1st argument
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:187:13: note: candidate template ignored: could not match
      'Local<type-parameter-0-0>' against 'v8::Isolate *'
  V8_INLINE Local(Local<S> that)
            ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:4126:22: note: passing argument to parameter 'context' here
      Local<Context> context, FunctionCallback callback,
                     ^
In file included from ../src/batch.cc:3:
In file included from ../../nan/nan.h:203:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337:37: error: too few arguments to function call, expected 2, have 1
  return v8::StringObject::New(value).As<v8::StringObject>();
         ~~~~~~~~~~~~~~~~~~~~~      ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:5380:3: note: 'New' declared here
  static Local<Value> New(Isolate* isolate, Local<String> value);
  ^
In file included from ../src/batch.cc:3:
In file included from ../../nan/nan.h:203:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337:58: error: expected '(' for function-style cast or type construction
  return v8::StringObject::New(value).As<v8::StringObject>();
                                         ~~~~~~~~~~~~~~~~^
../../nan/nan_implementation_12_inl.h:337:60: error: expected expression
  return v8::StringObject::New(value).As<v8::StringObject>();
                                                           ^
In file included from ../src/batch.cc:3:
../../nan/nan.h:1034:44: error: no matching member function for call to 'ToString'
      v8::Local<v8::String> string = from->ToString();
                                     ~~~~~~^~~~~~~~
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:2528:44: note: candidate function not viable: requires single argument
      'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                           ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:2544:35: note: candidate function not viable: requires single argument
      'isolate', but no arguments were provided
                    Local<String> ToString(Isolate* isolate) const);
                                  ^
In file included from ../src/batch.cc:3:
../../nan/nan.h:1044:37: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'char *'
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                    ^~~~
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:2738:26: note: passing argument to parameter 'isolate' here
  int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
                         ^
In file included from ../src/batch.cc:3:
../../nan/nan.h:1818:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
                           ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:3:
../../nan/nan.h:1824:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(key, value);
                           ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:3:
../../nan/nan.h:1830:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(index, value);
                           ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:3367:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:3:
../../nan/nan.h:1836:32: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
        New(persistentHandle)->Get(New(key).ToLocalChecked()));
                               ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:3412:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:3:
../../nan/nan.h:1842:48: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    return scope.Escape(New(persistentHandle)->Get(key));
                                               ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:3412:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:3:
../../nan/nan.h:1847:48: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    return scope.Escape(New(persistentHandle)->Get(index));
                                               ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:3416:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
  ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:3:
In file included from ../../nan/nan.h:2657:
../../nan/nan_object_wrap.h:24:25: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object,
      v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(persistent().IsNearDeath());
           ~~~~~~~~~~~~ ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../src/batch.cc:3:
In file included from ../../nan/nan.h:2657:
../../nan/nan_object_wrap.h:67:18: warning: 'MarkIndependent' is deprecated: Weak objects are always considered independent. Use
      TracedGlobal when trying to use EmbedderHeapTracer. Use a strong handle when trying to keep an object alive.
      [-Wdeprecated-declarations]
    persistent().MarkIndependent();
                 ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:563:3: note: 'MarkIndependent' has been explicitly marked deprecated
      here
  V8_DEPRECATED(
  ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:3:
In file included from ../../nan/nan.h:2657:
../../nan/nan_object_wrap.h:124:26: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object,
      v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(wrap->handle_.IsNearDeath());
           ~~~~~~~~~~~~~ ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../src/batch.cc:5:
In file included from ../src/database.h:18:
../src/leveldown.h:16:17: error: no matching member function for call to 'ToObject'
  return (!obj->ToObject().IsEmpty()
           ~~~~~^~~~~~~~
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument
      'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument
      'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
In file included from ../src/batch.cc:5:
In file included from ../src/database.h:18:
../src/leveldown.h:17:39: error: no matching member function for call to 'ToObject'
    && node::Buffer::HasInstance(obj->ToObject()))
                                 ~~~~~^~~~~~~~
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument
      'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument
      'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
In file included from ../src/batch.cc:5:
In file included from ../src/database.h:18:
../src/leveldown.h:18:33: error: no matching member function for call to 'ToObject'
    ? node::Buffer::Length(obj->ToObject())
                           ~~~~~^~~~~~~~
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument
      'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument
      'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
In file included from ../src/batch.cc:5:
In file included from ../src/database.h:18:
../src/leveldown.h:19:12: error: no matching member function for call to 'ToString'
    : obj->ToString()->Utf8Length();
      ~~~~~^~~~~~~~
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:2528:44: note: candidate function not viable: requires single argument
      'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                           ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:2544:35: note: candidate function not viable: requires single argument
      'isolate', but no arguments were provided
                    Local<String> ToString(Isolate* isolate) const);
                                  ^
In file included from ../src/batch.cc:5:
In file included from ../src/database.h:18:
../src/leveldown.h:30:62: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    v8::Local<v8::Value> obj = Nan::New<v8::Object>(handle)->Get(Nan::New<v8::String>("obj").ToLocalChecked());
                                                             ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:3412:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:5:
../src/database.h:31:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    _obj->Set(Nan::New("obj").ToLocalChecked(), obj);
          ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:8:
../src/common.h:19:17: error: no matching member function for call to 'Has'
    && options->Has(key)
       ~~~~~~~~~^~~
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:3449:37: note: candidate function not viable: requires 2 arguments, but
      1 was provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Has(Local<Context> context,
                                    ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:3455:37: note: candidate function not viable: requires 2 arguments, but
      1 was provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Has(Local<Context> context, uint32_t index);
                                    ^
In file included from ../src/batch.cc:8:
../src/common.h:20:16: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    ? options->Get(key)->BooleanValue()
               ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:3412:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:8:
../src/common.h:20:26: error: no matching member function for call to 'BooleanValue'
    ? options->Get(key)->BooleanValue()
      ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:2559:8: note: candidate function not viable: requires single argument
      'isolate', but no arguments were provided
  bool BooleanValue(Isolate* isolate) const;
       ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:2562:51: note: candidate function not viable: requires single argument
      'context', but no arguments were provided
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
In file included from ../src/batch.cc:8:
../src/common.h:30:17: error: no matching member function for call to 'Has'
    && options->Has(key)
       ~~~~~~~~~^~~
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:3449:37: note: candidate function not viable: requires 2 arguments, but
      1 was provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Has(Local<Context> context,
                                    ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:3455:37: note: candidate function not viable: requires 2 arguments, but
      1 was provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Has(Local<Context> context, uint32_t index);
                                    ^
In file included from ../src/batch.cc:8:
../src/common.h:31:17: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    && options->Get(key)->IsNumber()
                ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:3412:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:8:
../src/common.h:32:16: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    ? options->Get(key)->Uint32Value()
               ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:3412:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:8:
../src/common.h:32:38: error: too few arguments to function call, single argument 'context' was not specified
    ? options->Get(key)->Uint32Value()
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:2567:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/batch.cc:42:67: error: no matching member function for call to 'ToObject'
  Database* database = Nan::ObjectWrap::Unwrap<Database>(info[0]->ToObject());
                                                         ~~~~~~~~~^~~~~~~~
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument
      'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument
      'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
../src/batch.cc:72:69: error: too few arguments to function call, single argument 'context' was not specified
    maybeInstance = Nan::NewInstance(constructorHandle->GetFunction(), 1, argv);
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:5947:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/batch.cc:75:69: error: too few arguments to function call, single argument 'context' was not specified
    maybeInstance = Nan::NewInstance(constructorHandle->GetFunction(), 2, argv);
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8.h:5947:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/eklem/Library/Caches/node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
14 warnings and 20 errors generated.
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/eklem/git_modules/search-index/node_modules/level-out/node_modules/leveldown
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@3.0.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@3.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eklem/.npm/_logs/2019-09-23T07_52_43_413Z-debug.log
```
[2019-09-23T07_52_43_413Z-debug.log](https://github.com/fergiemcdowall/search-index/files/3641152/2019-09-23T07_52_43_413Z-debug.log)

**Comment by fergiemcdowall** [comment]
AFAIK this is a general issue node v12.x issue with modules that require C compilation, and is somewhat related to https://github.com/Level/levelup/issues/671

If we make sure that `search-index` uses `level@5.x` all the way down, then this issue _should_ disappear.

**Comment by eklem** [comment]
Seems it's memdown that is causing the problem. Bumped from v4.0.0 to v5.0.0. But now the last browser test fails. Will check if this is also true on Travis.

**Comment by eklem** [comment]
Ok, bumped memdown and added coding-down to devDependencies, and it works on Travis, but fails on one score on my Mac.

**Comment by eklem** [comment]
https://github.com/fergiemcdowall/search-index/pull/493

**Comment by eklem** [comment]
But, maybe we should move memdown example and testing into a library that depends on search-index? Could maybe get that library to update and run tests whenever search-index is updated? So, all the moving parts will still be there, but we get sorted out what's heads and tails.

**Comment by eklem** [comment]
I think it can be done through [GitHub Actions](https://github.com/features/actions)

**Comment by eklem** [comment]
Or, we can leave it for now, or just merge the PR. What do you think, @fergiemcdowall ?

**Comment by fergiemcdowall** [comment]
Not really sure off the top of my head- I will take a closer look...

**Comment by eklem** [comment]
Remembering now that `encoding-down` is part of how to get memdown work, but it's not a dependency it seems.

**Comment by eklem** [comment]
Guessing we can close this for now, since v2 is happening soon =)

**Comment by fergiemcdowall** [comment]
Good idea! It seems to be something to do with building `leveldown`, and the problem has probably been ironed out upstream.
