### ISSUE TITLE
can't get si.add to work without options defined before requiring search-index

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#88]
If i do like this:
```javascript
var si = require('search-index')

var batch = [
  {
    'id':'1',
    'title':'A really interesting document',
    'body':'This is a really interesting document',
    'metadata':['red', 'potato']
  },
  {
    'id':'2',
    'title':'Another interesting document',
    'body':'This is another really interesting document that is a bit different',
    'metadata':['yellow', 'potato']
  }
];
var batchName = 'twoDocs';
var filters = ['metadata'];

si.add({'batchName': batchName, 'filters': filters}, batch, function(err) {
  if (!err) console.log('indexed!');
});
```
... I get this error:
```javascript
si.add({'batchName': batchName, 'filters': filters}, batch, function(err) {
   ^
TypeError: Object function SearchIndex(options) {
  if (!(this instanceof SearchIndex))
    return new SearchIndex(options);
  //------------libs
  this.level = require('levelup');
  this.levelMultiply = require('level-multiply');
  this.winston = require('winston');
  _ = require('lodash');
  this.defaults = {
    indexPath: 'si',
    logLevel: 'info',
    logSilent: false
  };
  //initialize defaults options
  this.options = _.defaults(options || {}, this.defaults);
  this.calibrater = require('./indexing/calibrater.js');
  this.deleter = require('./indexing/deleter.js');
  this.docGetter = require('./search/docGetter.js');
  this.indexPeek = require('./indexing/indexPeek.js');
  this.indexer = require('./indexing/indexer.js');
  this.matcher = require('./matchers/matcher.js');
  this.replicator = require('./indexing/replicator.js');
  this.searcher = require('./search/searcher.js');
  this.searchIndexLogger = require('./logger/searchIndexLogger');
  this.indexes = (this.options && this.options.db)
    ? this.level(this.options.indexPath, {valueEncoding: 'json', db: this.options.db})
    : this.level(this.options.indexPath, {valueEncoding: 'json'});
  this.indexesMultiply = this.levelMultiply(this.indexes);
  this.searchIndexLogger.remove(this.winston.transports.Console);
  this.searchIndexLogger.add(this.winston.transports.Console, {silent: this.options.logSilent, level: this.options.logLevel});
  //is there a better way of doing this?
  var searcher = this.searcher;
  this.calibrater.getTotalDocs(this.indexes, function(err, totalDocs) {
    searcher.setTotalDocs(totalDocs);
  });
} has no method 'add'
    at Object.<anonymous> (/Users/eklem/node_modules/life-indexer/test.js:20:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

But if change the start of the file to this:
```javascript
var options = { indexPath: 'si2', logLevel: 'info', logSilent: false }
var si = require('search-index')(options)
```
...everything works okay! It's a minor since it's possible to work around pretty easy.

**Comment by eklem** [comment]
And kudos for good examples, so it's easy to test for bugs and issues!

**Comment by fergiemcdowall** [comment]
Hmmm, yes. How to do this.

Basically, at the moment, you need to do `var si = require('search-index')(options)` and not `var si = require('search-index')`. It would be nice if  `var si = require('search-index')` actually worked.

**Comment by mewwts** [comment]
Can you start search-index without params, ```require('search-index')()```?

**Comment by eklem** [comment]
That works!

**Comment by eklem** [comment]
So maybe only update `readme.md` and state that it's a breaking change?

**Comment by fergiemcdowall** [comment]
Yes, the readme should be updated

**Comment by fergiemcdowall** [comment]
quite a few breaking changes in 0.5.0

**Comment by eklem** [comment]
Should we mark breaking changes in readme.md ?

**Comment by fergiemcdowall** [comment]
The README should only pertain to the version that it is bundled with. Any docs in the WIKI could reference different versions.

I have tried to use [semver](https://nodesource.com/blog/semver-a-primer). My understanding of semver is that for all 0.x.x, the API should be regarded as unstable. From 1.x.x and upwards, a breaking API change should invoke an increment of the first digit (1.x.x -> 2.x.x)

I think.

**Comment by eklem** [comment]
Sounds good. But could we have one link to the wiki and one link to the issues from the documentation?

Today we have this in the documentation, and no issues list or performance tips:
`Search-index is in an alpha stage- meaning that it has been known to work quite well, but edge cases and portability may be challenging. Query-result is robust. See known issues and performance tips below.`
